export LS=$HOME/.local/share/
export IC=$LS/icons
export AP=$LS/applications
export docroot=/var/www/localhost/htdocs/
export DOCK='sudo docker run -ti -v "$PWD"/artifacts:/usr/portage/packages sabayon/builder-amd64'
export GHUB=$HOME/GitHub
export JAVA_HOME=/usr/lib/jvm/oracle-jdk-bin-1.8/bin
export JEF=https://github.com/JeffHoogland
export MW=/var/www/localhost/htdocs/w
  mw=MW
export PAK=$GHUB/Packer
export SSH_ASKPASS=/usr/lib64/misc/ssh-askpass
export WP=/var/www/localhost/htdocs/wp
  wp=WP
export WP_CON=$WP/wp-content
  WP_con=WP_CON
